INSTA_USERNAME: str = "INSTAGRAM USERNAME"
INSTA_PASSWORD: str = "INSTAGRAM PASSWORD"
DISCORD_WEBHOOK_URL: str = "DISCORD WEBHOOK URL"
DISCORD_NOTIFY_USERS: list = ["ARRAY OF NOTIFIED DISCORD ID"]
SITE_ENGINE_API_USER: str = "SITE ENGINE API USER"
SITE_ENGINE_API_SECRET: str = "SITE ENGIME API SECRET"