# Generated by Django 4.2 on 2023-04-13 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, verbose_name='contenu du post')),
                ('status', models.CharField(choices=[('N', 'Normal'), ('A', 'En attente de vérification'), ('H', 'Masqué')], default='N', max_length=1, verbose_name='état')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='post anonyme')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'permissions': (('create_posts', 'Peut créer des posts'), ('edit_own_posts', 'Peut modifier ses propres posts'), ('delete_own_posts', 'Peut supprimer ses propres posts'), ('hide_posts_from_other_users', "Peut masquer des posts (sans voir l'auteur)"), ('delete_posts_from_other_users', "Peut supprimer les posts des autres (sans voir l'auteur)"), ('view_posts_details', "Peut voir les détails des posts (dont l'auteur)")),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date du signalement')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.post', verbose_name='post signalé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='auteur du signalement')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'permissions': (('report_posts', 'Peut signaler des posts'), ('reset_reports', 'Reset reports')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post', verbose_name='post aimé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='auteur du like')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'permissions': (('like_posts', 'Peut aimer des posts'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='commentaire anonyme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'permissions': (('add_comments', 'Peut ajouter des commentaires'), ('delete_own_comments', 'Peut supprimer ses commentaires'), ('delete_comments_from_other_users', "Peut supprimer les commentaires des autres (sans voir l'auteur)"), ('view_comments_details', "Peut voir les détails des commentaires (dont l'auteur)")),
                'default_permissions': (),
            },
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_report_post_user'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_like_post_user'),
        ),
    ]
