# Generated by Django 4.0.4 on 2022-04-24 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('status', models.CharField(choices=[('N', 'Normal'), ('H', 'Masqué'), ('D', 'Supprimé')], default='N', max_length=1, verbose_name='état')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='post anonyme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'permissions': (('edit_other_users_posts', "Can edit other users' posts"), ('delete_other_users_posts', "Can delete other users' posts"), ('hide_unhide_posts', 'Can hide/unhide posts'), ('view_hidden_posts', 'Can view hidden posts'), ('show_author_name_when_anonymous', 'Can show author name when anonymous')),
            },
        ),
        migrations.CreateModel(
            name='PostReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date du signalement')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='blog.post', verbose_name='post signalé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to=settings.AUTH_USER_MODEL, verbose_name='auteur du signalement')),
            ],
            options={
                'verbose_name': 'signalement',
                'verbose_name_plural': 'signalements',
                'permissions': (('reset_reports', 'Can reset reports'), ('view_reports', 'Can view reports')),
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='blog.post', verbose_name='post aimé')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur aimant')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
                'permissions': (('reset_likes', 'Can reset likes'), ('view_likes', 'Can view likes')),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de creation')),
                ('is_anonymous', models.BooleanField(default=True, verbose_name='commentaire anonyme')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='auteur')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'commentaire',
                'verbose_name_plural': 'commentaires',
                'permissions': (('delete_other_users_comments', "Can delete other users' comments"), ('edit_other_users_comments', "Can edit other users' comments"), ('hide_unhide_comments', 'Can hide/unhide comments'), ('view_hidden_comments', 'Can view hidden comments')),
            },
        ),
        migrations.AddConstraint(
            model_name='postreport',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_report_post_user'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('post', 'user'), name='unique_like_post_user'),
        ),
    ]
